### ISSUE TITLE
Использование наиболее базового интерфейса

### ISSUE THREAD

**Issue by truenorthpaul** [Pasha1N/Calculator#3]
При выборе типа константы, поля, параметра, возвращаемого значения или переменной необходимо отдавать предпочтение наиболее базовому интерфейсу, который обладает требуемой функциональностью. Другими словами, не стоит использовать в качестве типа параметра метода тип `List<string>` если метод использует данный параметр только для обхода коллекции элементов. В такой ситуации достаточно было бы использовать тип `IEnumerable<string>`.

Поля, для которых данное правило не соблюдается:
- `Calculator.Canculator.arithmeticOperations`.
- `Calculator.Canculator.commands`.

**Comment by Pasha1N** [comment]
я там применяю индексацию и добавление !

**Comment by truenorthpaul** [comment]
Для добавления хватит `ICollection`, а там где индексация, можно упростить алгоритм, чтобы не было индексов вообще, и использовать `IEnumerable`.
